spring.application.name=ecommerce-backend
server.port=8080

# C?u hình k?t n?i MySQL (?ã cá nhân hóa tên DB)
spring.datasource.url=jdbc:mysql://localhost:3307/ecommercedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI Documentation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# H? tr? Enum không phân bi?t ch? hoa ch? th??ng
spring.jackson.mapper.accept-case-insensitive-enums=true

# X? lý l?i 404
spring.mvc.throw-exception-if-no-handler-found=true